spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://127.0.0.1:3306/chatting
    username: chat_db
    password: Dlehdgns0126!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat
      username: lee            # MongoDB 사용자 이름
      password: Dlehdgns0126!       # MongoDB 사용자 비밀번호

#  kafka:
#    bootstrap-servers: my-kafka:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.JsonSerializer
#    consumer:
#      auto-offset-reset: earliest
#      group-id: students
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer